version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
