import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { Logo } from "./_components/logo";
import { ArrowLeftIcon } from "@heroicons/react/20/solid";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="check24">
      <body className={`font-sans ${inter.variable}`}>
        <nav className="navbar flex justify-between bg-primary px-16 text-white">
          <Link href="/" className="btn btn-ghost text-xl">
            <ArrowLeftIcon className="mr-2 h-6 w-6" />
          </Link>
          <Logo />
        </nav>
        {children}
      </body>
    </html>
  );
}
