version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

        #   server:
        #     build:
        #       context: ./server
        #       dockerfile: Dockerfile
        #     ports:
        #       - "8080:8080"
        #     env_file:
        #       - ./server/.env
        #     environment:
        #       REDIS_URL: "redis://redis:6379"
        #     depends_on:
        #       - redis
